name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-43
      options: --privileged
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.1
      with:
        bundle: sticky.flatpak
        manifest-path: com.vixalien.sticky.json
        cache-key: flatpak-builder-${{ github.sha }}
        cache: true
        restore-cache: true
